apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc  # Change the service name to match the app
spec:
  selector:
    app: todo  # This should match the label used in the deployment
  ports:
    - protocol: TCP
      port: 80        # Expose service on port 80
      targetPort: 8000 # Match the containerPort in the deployment
      nodePort: 30007  # Optional: only if you need to expose via NodePort
  type: NodePort  # You can also use LoadBalancer if you need external access
